### PR TITLE
Remove 'function_exists' checks

### PR DESCRIPTION
**Pull request by iandunn**
Since we're not distributing this theme, we don't have to worry about conflicting functions, especially since they're prefixed. Having the extra condition and indentation hurts readability.

### CODE REVIEW

**Comment by iandunn** [comment]
We'll need to make sure that the `load_theme_textdomain()` call isn't added back if this is merged after #7 .

**Comment by 2ndkauboy** [comment]
So we don't want to have child themes? That's OK with me :) BTW: The indentation was only, to not break the WPCS ;)

**Comment by iandunn** [comment]
> So we don't want to have child themes? 

Ah, was that condition there in order to make the parent theme functions pluggable? I assumed it was just to avoid naming conflicts. 

Hmm, that could be worth keeping. I'm working on a PR to switch from function prefixes to namespaces, though, so if we did create a child theme we'd probably need to do the overriding a bit differently anyway.

I think we can figure out that best way to implement that if we ever decide to build a child theme for this.

**Comment by 2ndkauboy** [comment]
Yes, that was the purpose of the condition. But we probably create a `campsite-2018` rather than a child theme ;)

**Pull request merged**
